run_metadata:
  description: SEINRD Model
  local_data_registry_url: http://localhost:8000/api/
  remote_data_registry_url: https://data.scrc.uk/api/
  default_input_namespace: sonia
  default_output_namespace: sonia
  write_data_store: /Users/Soniam/.fair/data
  local_repo: /Users/Soniam/Desktop/git/FAIRDataPipeline/rSimpleModel
  script: |-
    R -f vignettes/SEINRD.R {CONFIG_DIR}
register:
- external_object: disease/sars_cov2/SEINRD_model/parameters/static_params
  namespace_name: BIOSS
  namespace_full_name: Biomathematics and Statistics Scotland
  namespace_website: https://www.bioss.ac.uk
  root: https://raw.githubusercontent.com/
  path: FAIRDataPipeline/rSimpleModel/main/inst/extdata/static_params_SEInRD.csv
  title: Static parameters of the model
  description: Static parameters of the model
  unique_name: SEINRD model parameters - Static parameters of the model
  alternate_identifier_type: SEINRD_model_params
  file_type: csv
  release_date: ${{DATETIME}}
  version: 0.${{DATE}}.0
  primary: True
- external_object: disease/sars_cov2/SEINRD_model/parameters/rts
  namespace_name: BIOSS
  namespace_full_name: Biomathematics and Statistics Scotland
  namespace_website: https://www.bioss.ac.uk
  root: https://raw.githubusercontent.com/
  path: FAIRDataPipeline/rSimpleModel/main/inst/extdata/Rt_beep.csv
  title: Values of Rt at time t
  description: Values of Rt at time t
  unique_name: SEINRD model parameters - Values of Rt at time t
  alternate_identifier_type: SEINRD_model_params
  file_type: csv
  release_date: ${{DATETIME}}
  version: 0.${{DATE}}.0
  primary: True
- external_object: disease/sars_cov2/SEINRD_model/parameters/efoi
  namespace_name: BIOSS
  namespace_full_name: Biomathematics and Statistics Scotland
  namespace_website: https://www.bioss.ac.uk
  root: https://raw.githubusercontent.com/
  path: FAIRDataPipeline/rSimpleModel/main/inst/extdata/efoi_all_dates.csv
  title: Effective force of infection at time t
  description: Effective force of infection at time t
  unique_name: SEINRD model parameters - Effective force of infection
  alternate_identifier_type: SEINRD_model_params
  file_type: csv
  release_date: ${{DATETIME}}
  version: 0.${{DATE}}.0
  primary: True
write:
- data_product: disease/sars_cov2/SEINRD_model/results/model_output
  description: SEINRD model results
  file_type: csv
- data_product: disease/sars_cov2/SEINRD_model/results/figure
  description: SEINRD output plot
  file_type: pdf
