run_metadata:
  description: Simple Model
  local_data_registry_url: http://localhost:8000/api/
  remote_data_registry_url: https://data.scrc.uk/api/
  default_input_namespace: sonia
  default_output_namespace: sonia
#  write_data_store: /Users/Soniam/.fair/data
  local_repo: /Users/Soniam/Desktop/git/FAIRDataPipeline/SimpleModel
  script: |-
    R -f vignettes/SEINRD_1.R {CONFIG_DIR}
read:
- data_product: disease/sars_cov2/simple_model/parameters/static_params
- data_product: disease/sars_cov2/simple_model/parameters/rts
- data_product: disease/sars_cov2/simple_model/parameters/efoi
write:
- data_product: disease/sars_cov2/simple_model/results/model_output
  description: SEINRD model results
  file_type: csv
- data_product: disease/sars_cov2/simple_model/results/figure
  description: SEINRD output plot
  file_type: pdf
