run_metadata:
  default_input_namespace: sonia
  description: SEINRD_model
  script: R -f inst/extdata/SEINRD.R --args ${{CONFIG_DIR}}

register:
- namespace: BioSS
  full_name: Biomathematics and Statistics Scotland
  website: https://ror.org/03jwrz939

- external_object: disease/sars_cov2/SEINRD_model/parameters/static_params
  namespace: BioSS
  root: https://raw.githubusercontent.com/
  path: FAIRDataPipeline/rSimpleModel/main/inst/extdata/static_params_SEInRD.csv
  title: Static parameters of the model
  description: Static parameters of the model
  unique_name: Simple model parameters - Static parameters of the model
  alternate_identifier_type: simple_model_params
  file_type: csv
  release_date: ${{DATETIME}}
  version: 1.0.0
  primary: True

- external_object: disease/sars_cov2/SEINRD_model/parameters/rts
  namespace: BioSS
  root: https://raw.githubusercontent.com/
  path: FAIRDataPipeline/rSimpleModel/main/inst/extdata/Rt_beep.csv
  title: Values of Rt at time t
  description: Values of Rt at time t
  unique_name: Simple model parameters - Values of Rt at time t
  alternate_identifier_type: simple_model_params
  file_type: csv
  release_date: ${{DATETIME}}
  version: 1.0.0
  primary: True

- external_object: disease/sars_cov2/SEINRD_model/parameters/efoi
  namespace: BioSS
  root: https://raw.githubusercontent.com/
  path: FAIRDataPipeline/rSimpleModel/main/inst/extdata/efoi_all_dates.csv
  title: Effective force of infection at time t
  description: Effective force of infection at time t
  unique_name: Simple model parameters - Effective force of infection
  alternate_identifier_type: simple_model_params
  file_type: csv
  release_date: ${{DATETIME}}
  version: 1.0.0
  primary: True

write:
- data_product: disease/sars_cov2/SEINRD_model/results/model_output
  description: SEINRD model results
  file_type: csv

- data_product: disease/sars_cov2/SEINRD_model/results/figure
  description: SEINRD output plot
  file_type: pdf
