on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
#          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@master
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install graphviz on ubuntu (for registry prov report)
        run:  |
              if [ ${{ runner.os }} == "Linux" ]; then
                  sudo apt-get install graphviz
              else
                  brew install graphviz
              fi
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install FAIR CLI and initialise rSimpleModel project
        run: |
          pip3 install fair-cli

      - name: git2r dependencies (for package deployment)
        run: sudo apt-get install -y libgit2-dev
      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: |
            rcmdcheck
            remotes
            pkgdown
          needs: website
      - name: Install R API system requirements (ubuntu-20.04)
        if: matrix.config.os == 'ubuntu-20.04'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'cat(remotes::system_requirements("ubuntu", "20.04"), sep = "\n")')

      - name: Install pdftools dependencies (for vignette)
        run: |
          sudo apt-get install -y libpoppler-cpp-dev
      - name: Deploy package
        run: |
          # Need to run CLI from a script via poetry run
          mkdir tmp
          echo "#!/bin/sh" >> ${{ github.workspace }}/tmp/tmp_file.sh
          echo "cd ../rSimpleModel" >> ${{ github.workspace }}/tmp/tmp_file.sh
          echo "git config --local user.name "$GITHUB_ACTOR" >> ${{ github.workspace }}/tmp/tmp_file.sh
          echo "git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com" >> ${{ github.workspace }}/tmp/tmp_file.sh
          echo "cd ../rSimpleModel" >> ${{ github.workspace }}/tmp/tmp_file.sh
          echo "Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'" >> ${{ github.workspace }}/tmp/tmp_file.sh
          chmod +x tmp/tmp_file.sh
          cd ${{ github.workspace }}
          python -m venv venv
          source venv/bin/activate
          fair registry install
          fair run --script "sh tmp/tmp_file.sh"

